CREATE DATABASE QUANLYVE
USE QUANLYVE

CREATE TABLE NGUOIDUNG
(
	MaDangNhap CHAR(20) PRIMARY KEY,
	TenNguoiDung VARCHAR(40),
	SoDienThoai INT,
	Email CHAR(40),
	NgaySinh SMALLDATETIME
)

CREATE TABLE SANBAY
(
	MaSanBay CHAR(20) PRIMARY KEY,
	TenSanBay VARCHAR(40)
)

CREATE TABLE HANGVE
(
	MaHangVe CHAR(20) PRIMARY KEY,
	TenHangVe VARCHAR(40)
)

CREATE TABLE CHUYENBAY
(
	MaChuyenBay CHAR(20) PRIMARY KEY,
	MaSanBayDi CHAR(20) FOREIGN KEY REFERENCES SANBAY(MaSanBay),
	MaSanBayDen CHAR(20) FOREIGN KEY REFERENCES SANBAY(MaSanBay),
	NgayBay SMALLDATETIME,
	GioBay TIME,
	Gia MONEY
)

CREATE TABLE KHACHHANG
(
	CMND CHAR(20) PRIMARY KEY,
	TenKhachHang VARCHAR(40),
	SoDienThoai INT,
	Email CHAR(40),
	NgaySinh SMALLDATETIME,
	MaChuyenBay CHAR(20) FOREIGN KEY REFERENCES CHUYENBAY(MaChuyenBay),
	MaSanBay CHAR(20) FOREIGN KEY REFERENCES SANBAY(MaSanBay)
)

CREATE TABLE CT_DATVE
(
	MaChuyenBay CHAR(20) FOREIGN KEY REFERENCES CHUYENBAY(MaChuyenBay),
	CMND CHAR(20) FOREIGN KEY REFERENCES KHACHHANG(CMND),
	MaHangVe CHAR(20) FOREIGN KEY REFERENCES HANGVE(MaHangVe),
	TinhTrangVe INT,
	NgayLap SMALLDATETIME,
	PRIMARY KEY(MaChuyenBay, CMND)
)

CREATE TABLE TRUNGGIAN
(
	MaSanBay CHAR(20) FOREIGN KEY REFERENCES SANBAY(MaSanBay),
	MaChuyenBay CHAR(20) FOREIGN KEY REFERENCES CHUYENBAY(MaChuyenBay),
	PRIMARY KEY(MaSanBay, MaChuyenBay)
)

CREATE TABLE BANVE
(
	MaChuyenBay CHAR(20) FOREIGN KEY REFERENCES CHUYENBAY(MaChuyenBay),
	CMND CHAR(20) FOREIGN KEY REFERENCES KHACHHANG(CMND),
	MaHangVe CHAR(20) FOREIGN KEY REFERENCES HANGVE(MaHangVe),
	MaSanBay CHAR(20) FOREIGN KEY REFERENCES SANBAY(MaSanBay),
	NgayLap SMALLDATETIME,
	TenKhachHang VARCHAR(40),
	SoDienThoai INT,
	Email CHAR(40),
	PRIMARY KEY(MaChuyenBay, CMND)
)

CREATE TABLE CT_HANGVE
(
	MaHangVe CHAR(20) FOREIGN KEY REFERENCES HANGVE(MaHangVe),
	MaChuyenBay CHAR(20) FOREIGN KEY REFERENCES CHUYENBAY(MaChuyenBay),
	SoLuong INT,
	PRIMARY KEY (MaHangVe, MaChuyenBay)
)
CREATE TABLE THAMSO
(
	SoSanBay	int,
	TGBay		time,
	SoSB_TG		int,
	TGDungMin	int,
	TGDungMax	int,
	SoHangVe	int,
	TgChamDV	time,
	TgHuyV		time,
)